
pipeline {
  agent{ label 'mini' }
  environment {
    ib = "${JOB_BASE_NAME}"   // Имя информационной базы
    DEBUG = false             // Режим отладки
    
    CLADDR = 'obr-app-11'     // Адрес кластера 1С
    DTpath = 'C:/1c/dt0'      // Каталог выгрузки dt файлов
    
    VER1C = '8.3.18.1483'     // Версия платформы 1С
    enCode = '0008'           // Код разрешения сеанса
    notyfyToken = '2djDy2SkydHJ-pE1b1cp5QaBy73yGPXx'
    Cnt = load './lib/Common.groovy'
    DPart = Cnt.formatDate(Cnt.TimeNow(), 'yyyy-MM-dd')  // Часть имени DT файла
    DTfile = "${DPart}_${ib}.dt" // Имя DT файла
    DT = "${DTpath}/${DTfile}"   // Полный путь к DT файлу
    FS = 0                       // Размер DT файла
    NOTE = "Start"               // Буферная переменная (не исп.)
  }
  options {
    disableConcurrentBuilds()
    timestamps()
  }
  stages {
    stage('1. Подготовка ИБ (блокировка, удаление сеансов)') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'ClusterAdmin', passwordVariable: 'clPASSWD', usernameVariable: 'clADMIN')
            , usernamePassword(credentialsId: 'IBadmin', passwordVariable: 'ibPASSWORD', usernameVariable: 'ibADMIN')]) {
            def command = """
              vrunner session kill --ras ${CLADDR}
              --cluster-admin ${clADMIN} --cluster-pwd ${clPASSWD}
              --ibconnection /s${CLADDR}\\${ib}
              --db ${ib} --db-user ${ibADMIN} --db-pwd ${ibPASSWORD}
              --uccode ${enCode} --v8version ${VER1C}
              """.replaceAll( /\n\s*/, " " )

            command = command.replace("\n", " ")
            if (DEBUG) { 
              bat "echo "+ command + " > COMMAND.1.txt" 
              echo "command: " + command
            }

            bat """chcp 65001
                ${ command } """
          }
        }
      }
    }
    stage ("2. Выгрузка ИБ в dt файл") {
      steps {
        script {

          withCredentials([usernamePassword(credentialsId: 'IBadmin', 
              passwordVariable: 'ibPASSWORD', usernameVariable: 'ibADMIN')]) {
            command = """
              vrunner dump ${DT} 
              --ibconnection /s${CLADDR}\\${ib}
              --db-user ${ibADMIN} --db-pwd ${ibPASSWORD}
              --uccode ${enCode} --v8version ${VER1C}
            """.replaceAll( /\n\s*/, " " )
            command = command.replace("\n", " ")
            if (DEBUG) { 
              bat "echo "+ command + " > COMMAND.2.txt" 
              echo "command: " + command
            }
            RETURN_STATUS = 1
            
            // for (int i = 1; i < 5; ++i) {
            //   if ( RETURN_STATUS == 0 ) {
            //     break
            //   } else {
            //     echo ">>> ПОПЫТКА " + i.toString() + " <<<"
            //     RETURN_STATUS = bat returnStatus: true, script: """ chcp 65001 \n ${command} """
            //   }
            // }
          }
          echo "*** Class: __" + DT.getClass() + "__"
          FS = Cnt.psize("${DT}")
          echo "1. " + DT + " FS: " + FS 
          // File fl = new File("C:/1c/dt0/2021-10-22_mc_zup_111.dt")
            
          // File fm = new File("C:\\1c\\dt0\\2021-10-22_mc_zup_111.dt")
          //   echo "1. " + fm + " ex. " + fm.exists() 
          // File ft = new File("C:\\\\1c\\\\dt0\\\\2021-10-22_mc_zup_111.dt")
          //   echo "1. " + ft + " ex. " + ft.exists() 
          // fsize = (double) fl.length()/(1024*1024)
          //   echo "2. " + fsize
          // NOTE = fsize.round(0) + 'mb'
          //   echo "3. " + NOTE
        }
      }
    }
  }
  post {
    cleanup { script {
        echo "POST: Снятие блокировки с ИБ"
        withCredentials([usernamePassword(credentialsId: 'ClusterAdmin', passwordVariable: 'clPASSWD', usernameVariable: 'clADMIN')
            , usernamePassword(credentialsId: 'IBadmin', passwordVariable: 'ibPASSWORD', usernameVariable: 'ibADMIN')]) {
            def command = """
              vrunner session unlock
              --ras ${ CLADDR }
              --cluster-admin ${ clADMIN }
              --cluster-pwd ${ clPASSWD }
              --ibconnection /s${ CLADDR }\\${ ib }
              --db ${ ib } --db-user ${ ibADMIN }
              --db-pwd ${ ibPASSWORD }
              --uccode ${ enCode }
              --v8version ${ VER1C } """.replaceAll( /\n\s*/, " " )

            

            if (DEBUG) { 
              bat "echo "+ command + " > COMMAND.P.txt" 
              echo "command: " + command
            }

            bat """chcp 65001>nul
                $command"""
            // bat "set"
        }

    } }
    success { script {
       
       echo "########### РАЗМЕР ### ${NOTE}"

        notifyEvents message: "${BUILD_DISPLAY_NAME} Выгрузка <b>${JOB_BASE_NAME}</b> завершена успешно в файл ```${DT}``` ", 
          token: notyfyToken
          echo "${DT} file FS ${FS}"
    } }
    unsuccessful { script {
      
        notifyEvents message: "${BUILD_DISPLAY_NAME} Выгрузка <b>${JOB_BASE_NAME}</b> завершена с ошибками", 
          token: notyfyToken
    } }
  }
}


