
pipeline {
  agent{ label 'mini' }
  environment {
    ib = "${JOB_BASE_NAME}"
    DEBUG = false
    
    CLADDR = 'obr-app-11'
    DTpath = '/1c/dt0'
    
    VER1C = '8.3.18.1483'
    enCode = '0008'
    notyfyToken = '2djDy2SkydHJ-pE1b1cp5QaBy73yGPXx'
    Cnt = load './lib/Common.groovy'
    DPart = Cnt.formatDate(Cnt.TimeNow(), 'yyyy-MM-dd')
    DTfile = "${DPart}_${ib}.dt"
    DT = "${DTpath}/${DTfile}"
    FS = 0
    NOTE = "Start"
  }
  options {
    disableConcurrentBuilds()
    timestamps()
  }
  stages {
    stage('1. Подготовка ИБ (блокировка, удаление сеансов)') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'ClusterAdmin', passwordVariable: 'clPASSWD', usernameVariable: 'clADMIN')
            , usernamePassword(credentialsId: 'IBadmin', passwordVariable: 'ibPASSWORD', usernameVariable: 'ibADMIN')]) {
            def command = """vrunner session kill --ras ${CLADDR}
              --cluster-admin ${clADMIN} --cluster-pwd ${clPASSWD}
              --ibconnection /s${CLADDR}\\${ib}
              --db ${ib} --db-user ${ibADMIN} --db-pwd ${ibPASSWORD}
              --uccode ${enCode} --v8version ${VER1C}
              """
            command = command.replace("\n", " ")
            if (DEBUG) { 
              bat "echo "+ command + " > COMMAND.1.txt" 
              echo "command: " + command
            }

            bat """chcp 65001
                ${ command } """
          }
        }
      }
    }
    stage ("2. Выгрузка ИБ в dt файл") {
      steps {
        script {

          withCredentials([usernamePassword(credentialsId: 'IBadmin', 
              passwordVariable: 'ibPASSWORD', usernameVariable: 'ibADMIN')]) {
            command = """vrunner dump ${DT} 
              --ibconnection /s${CLADDR}\\${ib}
              --db-user ${ibADMIN} --db-pwd ${ibPASSWORD}
              --uccode ${enCode} --v8version ${VER1C}
            """
            command = command.replace("\n", " ")
            if (DEBUG) { 
              bat "echo "+ command + " > COMMAND.2.txt" 
              echo "command: " + command
            }
            RETURN_STATUS = 1
            
            // for (int i = 1; i < 5; ++i) {
            //   if ( RETURN_STATUS == 0 ) {
            //     break
            //   } else {
            //     echo ">>> ПОПЫТКА " + i.toString() + " <<<"
            //     RETURN_STATUS = bat returnStatus: true, script: """ chcp 65001 \n ${command} """
            //   }
            // }
          }
          // FS = Cnt.filesizeMb(DT)
          File fl = new File("C:/1C/dt0/2021-10-22_mc_zup_111.dt")
            echo "1. " + fl + " ex. " + fl.exists() 
          File fm = new File("C:\\1C\\dt0\\2021-10-22_mc_zup_111.dt")
            echo "1. " + fm + " ex. " + fm.exists() 
          fsize = (double) fl.length()/(1024*1024)
            echo "2. " + fsize
          NOTE = fsize.round(0) + 'mb'
            echo "3. " + NOTE
        }
      }
    }
  }
  post {
    cleanup { script {
        echo "POST: Снятие блокировки с ИБ"
        withCredentials([usernamePassword(credentialsId: 'ClusterAdmin', passwordVariable: 'clPASSWD', usernameVariable: 'clADMIN')
            , usernamePassword(credentialsId: 'IBadmin', passwordVariable: 'ibPASSWORD', usernameVariable: 'ibADMIN')]) {
            def command = """vrunner session unlock
              --ras ${ CLADDR }
              --cluster-admin ${ clADMIN }
              --cluster-pwd ${ clPASSWD }
              --ibconnection /s${ CLADDR }\\${ ib }
              --db ${ ib } --db-user ${ ibADMIN }
              --db-pwd ${ ibPASSWORD }
              --uccode ${ enCode }
              --v8version ${ VER1C } """

            command = command.replace("\n", " ")
            command = command.replace("\t", " ")
            command = command.replace("  ", " ")
            if (DEBUG) { 
              bat "echo "+ command + " > COMMAND.P.txt" 
              echo "command: " + command
            }

            bat """chcp 65001>nul
                $command"""
            // bat "set"
        }

    } }
    success { script {
       
       echo "########### РАЗМЕР ### ${NOTE}"

        notifyEvents message: "${BUILD_DISPLAY_NAME} Выгрузка <b>${JOB_BASE_NAME}</b> завершена успешно в файл ```${DT}``` ", 
          token: notyfyToken
          echo "${DT} file FS ${FS}"
    } }
    unsuccessful { script {
      
        notifyEvents message: "${BUILD_DISPLAY_NAME} Выгрузка <b>${JOB_BASE_NAME}</b> завершена с ошибками", 
          token: notyfyToken
    } }
  }
}


